config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :events
  resources :artists
  get '/home' => 'home#index'
  get '/' => 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id                   :integer          not null, primary key
#  name                 :string
#  facebook_link        :string
#  intagram_link_string :string
#  spotify_link         :string
#  donation_link        :string
#  hire_link            :string
#  genre                :string
#  profile_picture      :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#

class Artist < ApplicationRecord
  has_many :artist_has_events
  has_many :events, through: :artist_has_events
end

app/models/artist_has_event.rb
class ArtistHasEvent < ApplicationRecord
  belongs_to :event
  belongs_to :artist
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id            :integer          not null, primary key
#  date          :string
#  location      :string
#  event_picture :string
#  buy_link      :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Event < ApplicationRecord
  has_many :artist_has_events
  has_many :artists, through: :artist_has_events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :facebook_link, :intagram_link_string, :spotify_link, :donation_link, :hire_link, :genre, :profile_picture)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :location, :event_picture, :buy_link, :name, :price)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :artist_name %>
  </div>

  <div class="field">
    <%= form.label :facebook_link %>
    <%= form.text_field :facebook_link, id: :artist_facebook_link %>
  </div>

  <div class="field">
    <%= form.label :intagram_link_string %>
    <%= form.text_field :intagram_link_string, id: :artist_intagram_link_string %>
  </div>

  <div class="field">
    <%= form.label :spotify_link %>
    <%= form.text_field :spotify_link, id: :artist_spotify_link %>
  </div>

  <div class="field">
    <%= form.label :donation_link %>
    <%= form.text_field :donation_link, id: :artist_donation_link %>
  </div>

  <div class="field">
    <%= form.label :hire_link %>
    <%= form.text_field :hire_link, id: :artist_hire_link %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre, id: :artist_genre %>
  </div>

  <div class="field">
    <%= form.label :profile_picture %>
    <%= form.text_field :profile_picture, id: :artist_profile_picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<header class="rl-header">
  <%= link_to home_path, class: 'branding' do %>
    <%= image_tag('logo.svg') %>
  <% end %>
  <h1 class="title">Artistas</h1>
</header>

<main class="rl-main">

  <p id="notice"><%= notice %></p>

  <div class="rl-cards">
    <% @artists.each do |artist| %>
      <%= link_to artist, class: 'rl-card' do %>
        <img class="picture" src="<%= artist.profile_picture %>" alt="">
        <div class="info">
          <h4><%= artist.name %></h4>
          <h6><%= artist.genre %></h6>
        </div>
      <% end %>
    <% end %>
  </div>

  <%
=begin%>
 <%= link_to 'New Artist', new_artist_path %> 
<%
=end%>

</main>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<header class="rl-header">
  <%= link_to home_path, class: 'branding' do %>
    <%= image_tag('logo.svg') %>
  <% end %>
  <h1 class="title"><%= link_to 'Artistas', artists_path %> › <%= @artist.name %></h1>
</header>

<main class="rl-main">

  <p id="notice"><%= notice %></p>

  <img class="picture" src="<%= @artist.profile_picture %>" alt="">

  <div class="buttons" style="overflow: auto;">
    <%= link_to 'Doar para o artista', @artist.donation_link, class: 'rl-button' %>
    <%= link_to 'Contratar o artista', @artist.hire_link, class: 'rl-button' %>
  </div>

  <h2><%= @artist.name %></h2>

  <h3><%= @artist.genre %></h3>

  <p><%= link_to 'Página do Facebook', @artist.facebook_link %></p>

  <p><%= link_to 'Página do Instagram', @artist.intagram_link_string %></p>

  <p><%= link_to 'Página do Spotify', @artist.spotify_link %></p>

  <h4>Eventos em que o artista vai tocar:</h4>
  <h6>Evento 1</h6>
  <h6>Evento 2</h6>
  <h6>Evento 3</h6>

</main>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date, id: :event_date %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :event_location %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :price %>
  </div>

  <div class="field">
    <%= form.label :event_picture %>
    <%= form.text_field :event_picture, id: :event_event_picture %>
  </div>

  <div class="field">
    <%= form.label :buy_link %>
    <%= form.text_field :buy_link, id: :event_buy_link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<header class="rl-header">
  <%= link_to home_path, class: 'branding' do %>
    <%= image_tag('logo.svg') %>
  <% end %>
  <h1 class="title">Rolês</h1>
</header>

<main class="rl-main">

  <p id="notice"><%= notice %></p>

  <div class="rl-cards">
    <% @events.each do |event| %>
      <%= link_to event, class:'rl-card' do %>
        <img class="picture" src="<%= event.event_picture %>" alt="">
        <div class="info">
          <h4><%= event.name %></h4>
          <h6><%= event.date %></h6>
          <h6><%= event.price %></h6>
          <h6><%= event.location %></h6>
        </div>
      <% end %>
    <% end %>
  </div>

  <%
=begin%>
 <%= link_to 'New Event', new_event_path %> 
<%
=end%>

</main>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<header class="rl-header">
  <%= link_to home_path, class: 'branding' do %>
    <%= image_tag('logo.svg') %>
  <% end %>
  <h1 class="title"><%= link_to 'Eventos', events_path %> › <%= @event.date %></h1>
</header>

<main class="rl-main">

  <p id="notice"><%= notice %></p>

  <img class="picture" src="<%= @event.event_picture %>" alt="">

  <div class="buttons" style="overflow: auto;">
    <%= link_to 'Ingressos', @event.buy_link, class: 'rl-button' %>
  </div>

  <h2><%= @event.date %></h2>

  <h3><%= @event.name %></h3>

  <h3><%= @event.location %></h3>

  <h3><%= @event.price %></h3>

  <h3><%= @event.date %></h3>

  <p><%= link_to 'Página do Facebook', '' %></p>

  <h4>Artistas que vão tocar nesse evento:</h4>
  <h6>Artista 1</h6>
  <h6>Artista 2</h6>
  <h6>Artista 3</h6>

</main>

app/views/home/index.html.erb
<header class="rl-header -large">
  <%= link_to home_path, class: 'branding' do %>
    <%= image_tag('logo.svg') %>
  <% end %>
</header>

<main class="rl-main">

  <%= link_to 'Artistas', artists_path, class: 'rl-button' %>
  <%= link_to 'Rolês', events_path, class: 'rl-button' %>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rolelocal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body class="rl-body">
    <%= yield %>
  </body>
</html>